; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

build_flags =
  -DRADIOLIB_EXCLUDE_SX127X

lib_deps =
  milesburton/DallasTemperature @ ^3.11.0
  paulstoffregen/OneWire @ ^2.3.8
  adafruit/Adafruit MPU6050 @ ^2.2.6
  adafruit/Adafruit INA219 @ ^1.2.1
  adafruit/RTClib @ ^2.1.4
  adafruit/Adafruit BusIO @ ^1.16.1
  jgromes/RadioLib @ ^6.6.0

extra_scripts = post:generate_hex.py