[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

build_flags =
  -DRADIOLIB_EXCLUDE_SX127X

lib_deps =
  jgromes/RadioLib @ ^6.6.0
  bblanchon/ArduinoJson @ ^7.0.0
  ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.4.0

board_build.filesystem = spiffs